repo_url: https://felipefreire-gf.github.io/seguidorDeLinha/
repo_name: 2025.1-Seguidor de Linha

site_name: Seguidor de Linha - Titans

nav:
# - Landing Page: landing.html
  - Home: index.md

#  - Atas:
#    - Sprint 1:
#        - Ata 1: "atas-reuniao/ata-reuniao-1.md"

  - Links:
    - Apresentação 1: "links/links.md" 

  - Baby Orangutan:
    - Orangutan: "baby/baby.md" 
    - Tutorial Firmware Uno: "baby/uploadUno.md"
    - Estado Atual: "baby/estadoAtt.md"
  

theme:
  logo: view/logoSL.png
  font:
    text: Montserrat
  name: material
  features:
    - content.code.annotate
    - content.tabs.link
    - header.autohide
    - navigation.expand
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - navigation.path

  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: amber
      accent: amber
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: #2c2c7c
      accent: #2c2c7c
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

  icon:
    repo: fontawesome/brands/git-alt
